import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { AnnotationStore } from "@acciaccatura/core";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { createServer } from "../../src/server.js";

/**
 * The golden API file.
 *
 * The MCP surface is a contract with consumers we do not control: every tool
 * name, every argument, and every word of every description an agent reads to
 * decide when to call something. Those may only ever be added to — see
 * standards/stable-contracts.md, which has been asking for this file since the
 * policy was written.
 *
 * The point is that a change here cannot happen quietly. Renaming a tool,
 * dropping an argument, or rewording a description are all one-character edits
 * in the source and all of them reach real agents. This test makes each of them
 * a visible diff that someone has to look at and agree to.
 *
 * To accept a change you have decided is right:
 *
 *     UPDATE_GOLDEN=1 npm test --workspace @acciaccatura/mcp-server
 *
 * and read the diff before you commit it. The question to answer is not "did I
 * mean to do this" but "is this additive" — a new tool or a new optional
 * argument is fine, a rename or a removal waits for a major version.
 */
const GOLDEN = join(dirname(fileURLToPath(import.meta.url)), "surface.golden.md");

let root: string;

beforeEach(async () => {
  root = await mkdtemp(join(tmpdir(), "acc-surface-"));
});

afterEach(async () => {
  await rm(root, { recursive: true, force: true });
});

/**
 * A set the prompts can be rendered against.
 *
 * Every prompt needs a set that exists, and its message states what the set
 * holds, so the fixture has to be fixed for the golden file to be stable. One
 * open note is the smallest thing that makes all three render.
 */
const GOLDEN_SCOPE = "pr/142";

/** Connect a client to a server over the same path an agent host uses. */
async function connect(): Promise<Client> {
  const store = new AnnotationStore(join(root, ".acciaccatura", "annotations.json"));
  await store.load();
  await store.add({
    body: "a note, so the set exists",
    anchor: { file: "src/pay.ts", startLine: 1, endLine: 1, snapshot: "export function pay(a) {" },
    provenance: "agent",
    scope: GOLDEN_SCOPE,
    order: 1,
  });
  const server = createServer(store, root);
  const [clientT, serverT] = InMemoryTransport.createLinkedPair();
  await server.connect(serverT);
  const client = new Client({ name: "golden", version: "0" });
  await client.connect(clientT);
  return client;
}

const byName = <T extends { name: string }>(items: readonly T[]): T[] =>
  [...items].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

/**
 * Everything an agent can see, as text.
 *
 * Written in reading order rather than as raw JSON, because the thing being
 * guarded is what an agent is told, and a reviewer has to be able to read the
 * diff and judge it.
 */
async function describeSurface(client: Client): Promise<string> {
  const out: string[] = [
    "# Acciaccatura MCP surface",
    "",
    "Generated by surface.test.ts. Do not edit by hand.",
    "",
    "This is a contract with agents we do not control. Additions are fine;",
    "renames, removals and re-typings wait for a major version. See",
    "standards/stable-contracts.md.",
    "",
  ];

  const { tools } = await client.listTools();
  out.push(`## Tools (${tools.length})`, "");
  for (const tool of byName(tools)) {
    out.push(`### ${tool.name}`, "");
    out.push(`title: ${tool.title ?? "(none)"}`, "");
    out.push("description:", "", tool.description ?? "(none)", "");
    out.push("input schema:", "", "```json", JSON.stringify(tool.inputSchema, null, 2), "```", "");
  }

  const { resources } = await client.listResources();
  const { resourceTemplates } = await client.listResourceTemplates();
  out.push(`## Resources (${resources.length} fixed, ${resourceTemplates.length} templated)`, "");
  for (const r of byName(resources)) {
    out.push(`### ${r.name}`, "", `uri: ${r.uri}`, `mimeType: ${r.mimeType ?? "(none)"}`, "");
    out.push("description:", "", r.description ?? "(none)", "");
  }
  for (const t of byName(resourceTemplates)) {
    out.push(`### ${t.name} (template)`, "");
    out.push(`uriTemplate: ${t.uriTemplate}`, `mimeType: ${t.mimeType ?? "(none)"}`, "");
    out.push("description:", "", t.description ?? "(none)", "");
  }

  const { prompts } = await client.listPrompts();
  out.push(`## Prompts (${prompts.length})`, "");
  for (const p of byName(prompts)) {
    out.push(`### ${p.name}`, "");
    out.push(`title: ${p.title ?? "(none)"}`, "");
    out.push("description:", "", p.description ?? "(none)", "");
    const args = (p.arguments ?? []).map(
      (a) => `- ${a.name}${a.required ? " (required)" : ""}: ${a.description ?? "(none)"}`,
    );
    out.push("arguments:", "", ...(args.length > 0 ? args : ["(none)"]), "");

    // The message is the procedure. It is the longest thing an agent reads from
    // this server and the easiest to reword by accident, so it belongs here
    // rather than being left to a handful of regexes.
    const got = await client.getPrompt({ name: p.name, arguments: { scope: GOLDEN_SCOPE } });
    const text = got.messages
      .map((m) => `[${m.role}]\n${m.content.type === "text" ? m.content.text : `(${m.content.type})`}`)
      .join("\n\n");
    out.push(`message, for a set named ${GOLDEN_SCOPE} holding one open note:`, "", text, "");
  }

  return `${out.join("\n").trimEnd()}\n`;
}

describe("the published surface", () => {
  it("matches the golden file, word for word", async () => {
    const client = await connect();
    const actual = await describeSurface(client);
    await client.close();

    if (process.env.UPDATE_GOLDEN) {
      await writeFile(GOLDEN, actual, "utf8");
      return;
    }

    const expected = await readFile(GOLDEN, "utf8").catch(() => undefined);
    expect(
      expected,
      `${GOLDEN} is missing. Create it with UPDATE_GOLDEN=1 and read what it says.`,
    ).toBeDefined();

    // A tool name, an argument, or a single reworded sentence in a description
    // all reach agents we do not control. If this diff is a surprise, it is a
    // defect; if it is deliberate, check it is ADDITIVE before updating the
    // file with UPDATE_GOLDEN=1.
    expect(actual).toBe(expected);
  });

  it("describes every tool, resource and prompt, so nothing can be added unseen", async () => {
    const client = await connect();
    const golden = await readFile(GOLDEN, "utf8");
    const { tools } = await client.listTools();
    const { prompts } = await client.listPrompts();
    const { resourceTemplates } = await client.listResourceTemplates();
    await client.close();

    // A generator that quietly skipped a section would keep this file green
    // while the surface grew underneath it.
    for (const name of [...tools, ...prompts, ...resourceTemplates].map((x) => x.name)) {
      expect(golden, `${name} is not in the golden file`).toContain(`### ${name}`);
    }
    expect(golden).toContain(`## Tools (${tools.length})`);
    expect(golden).toContain(`## Prompts (${prompts.length})`);
  });
});
